### ISSUE TITLE
La fonction strlwr transforme les lettres en miniscule

### ISSUE THREAD

**Issue by hlide** [pac2man/mzf2tape#1]
https://github.com/pac2man/mzf2tape/blob/2108fcad03d2dc931aaad125cc67164beb53f543/mz2tape.ino#L443
https://github.com/pac2man/mzf2tape/blob/2108fcad03d2dc931aaad125cc67164beb53f543/mz2tape.ino#L453
https://github.com/pac2man/mzf2tape/blob/2108fcad03d2dc931aaad125cc67164beb53f543/mz2tape.ino#L463
https://github.com/pac2man/mzf2tape/blob/2108fcad03d2dc931aaad125cc67164beb53f543/mz2tape.ino#L473

Ces lignes retourneront donc toujours un résultat faux. Pour le premier, il suffit simplement de comparer à ".mzf". Pareil pour ".mzt", ".m12" et ".bin". En fait, la bonne ligne qui compare avec ".mzf" fonctionnera avec toutes les combinaisons ".Mzf", ".MZf", "mzF", ".MZF", etc. en raison de l'utilisation de la fonction strlwr.

De fait, il n'est besoin que de quatre tests (.mzf, .mzt, .m12 et .bin) à faire au lieu du double actuel pour en réalité couvrir toutes les combinaisons majuscules/miniscules.

**Comment by pac2man** [comment]
Merci pour cette précision. je n'avais pas creusé cette fonction (et de loin). Je vais modifier le projet...
